name: Update AdGuard DNS Rewrites

on:
  push:
    paths:
      - "dns_rewrites.json"

jobs:
  update-dns:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update AdGuard DNS Rewrites
        uses: lemisieur-services/adguard-rewrite@v1
        with:
          DNS_FILE: dns_rewrites.json
          ADGUARD_USERNAME: ${{ secrets.ADGUARD_USERNAME }}
          ADGUARD_PASSWORD: ${{ secrets.ADGUARD_PASSWORD }}
          ADGUARD_URL: ${{ secrets.ADGUARD_URL }}
